### ISSUE TITLE
Use github actions

### ISSUE THREAD

**Issue by pkinglinz** [linz/nz-buildings#357]
### User Story

Replace travis with github actions.

Currently blocked due to docker compose.
Need docker compose as we use both qgis and postgis containers.

to seek @blacha advise re docker compose

#### Acceptance Criteria
- [x] db testing works
- [ ] plugin testing works
- [x] linting testing works
- [ ] deployment works

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by blacha** [comment]
the issue around `/dev/tty` not existing is caused by a combination of the way that the qgis test runner is invoked, and that github actions does not seem to assign a TTY.

the runner is invoked using a wrapper that captures all the output and then `tee`'s it into the tty to get it to display on the console.
https://github.com/planetfederal/qgis-testing-environment-docker/blob/master/qgis_testrunner.sh#L10 

This could possibly be worked around using something like 
```bash
QGIS_TEST_MODULE=${TEST_NAME} 
unbuffer qgis --nologo --code /usr/bin/qgis_testrunner.py $TEST_NAME  2>/dev/null | tee test.log
OUTPUT=$(cat test.log)
```

Although it looks like it would be just easier to remove the `qgist_testrunner.sh` from the pipeline and invoke the qgis testing command directly.

**Comment by dwsilk** [comment]
The code linked above was moved into the main QGIS codebase, here it is in the release we're using:

https://github.com/qgis/QGIS/blob/release-3_4/.docker/qgis_resources/test_runner/qgis_testrunner.sh#L14

Just in case we were going to raise an issue, it should be on the QGIS repo, not `planetfederal/qgis-testing-environment-docker`.
